# Dockerfile.base
FROM python:3.10.15-slim

# 设置工作目录
WORKDIR /app

# 安装系统依赖
RUN apt update && apt-get install libgl1 libglib2.0-0 libgomp1 -y
RUN pip install gunicorn
# 安装 PaddlePaddle
RUN python -m pip install paddlepaddle==2.5.2 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

# 复制 requirements.txt 并安装 Python 依赖
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
