name: Docker Build and Push

on:
  push:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.kexie.space
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -f deploy/Dockerfile -t docker.kexie.space/wilinz/image-captcha-ocr-service:latest --push . &
          docker build -f deploy/Dockerfile_cuda -t docker.kexie.space/wilinz/image-captcha-ocr-gpu-service:latest --push . &
